(define (prep-rule-0)
  (if (match-rule? '((_obj $be $var2) ($prep $var1 $var2)))
      (rule-applied "prep-rule-0")
      )
  )
(define (prep-rule-1)
  (if (match-rule? '((_subj $be $var0) ($prep $var1 $var2)))
      (rule-applied "prep-rule-1")
      )
  )
(define (prep-rule-2)
  (if (match-rule? '((_predadj $var1 $var0) ($prep $var1 $var2)))
      (rule-applied "prep-rule-2")
      )
  )
(define (prep-rule-3)
  (if (match-rule? '((_obj $var1 $var0) ($prep $var1 $var2)))
      (rule-applied "prep-rule-3")
      )
  )
(define (prep-rule-4)
  (if (match-rule? '((_subj $var1 $var0) ($prep $var1 $var2)))
      (rule-applied "prep-rule-4")
      )
  )

(define (run-rules)
  (prep-rule-0)
  (prep-rule-1)  
  (prep-rule-2)
  (prep-rule-3)
  (prep-rule-4)
)
(run-rules)
